# H2 Properties
spring:
  datasource:
    url: jdbc:h2:mem:mfpe
    password: root
    username: root
    driver-class-name: org.h2.Driver
    
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default

  application:
    name: vendor-service
  
server:
  port: 8003

#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka